# FOSElasticaBundle (search&filter engine) library configuration

fos_elastica:
    #serializer: ~
    clients:
        default:
            host: "%fos_elastica.host%"
            port: "%fos_elastica.port%"
    indexes:
      archive:
        index_name: archive_entries
        client: default
        settings:
          index:
            analysis:
              analyzer:
                archive:
                  type: keyword
                  filter: [lowercase]
                  tokenizer: keyword
        types:
          archive_factories:
            properties:
              id: ~
              factoryName: ~
          archive_settings:
            properties:
              id: ~
              factoryId: ~
              settingsName: ~
            _parent:
              type: "archive_factories"
              identifier: "id"
              property: "id"
          archive_entries:
            properties:
              factory:
                type: "object"
                properties:
                  id: ~
                  factoryName: ~
              setting:
                type: "object"
                properties:
                  id: ~
                  settingName: ~
              year:
                type: integer
              archiveNumber: {analyzer: archive}
              registerNumber: {analyzer: archive}
              contractNumber: {analyzer: archive}
              fullConclusionName: {analyzer: archive}
              cataloguePath: ~
              deleted: ~
              deleted_children: ~
            persistence:
              driver: orm
              model: App\Entity\ArchiveEntryEntity
              finder: ~
              provider: ~
              listener: ~
              repository: ~ #App\Repository\ArchiveEntrySearchRepository
              elastica_to_model_transformer:
                query_builder_method: createEntriesAndErrorsQueryBuilder
