imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ru
    app_locales: ru|en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    #translator: ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    #trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    cache: false
    paths:
        '%kernel.root_dir%/../vendor/ninsuo/symfony-collection': symfony-collection
    form_themes:
            - '@symfony-collection/jquery.collection.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
          enum: string
          set: string
          varbinary: string
          tinyblob: text
        options:
          1002: "SET NAMES 'UTF8'"
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
                    default:
                        naming_strategy: doctrine.orm.naming_strategy.underscore
                        auto_mapping: true
                        #stof_doctrine_extensions configuration
                        mappings:
                            gedmo_translatable:
                                type: annotation
                                prefix: Gedmo\Translatable\Entity
                                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                                alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
                                is_bundle: false
                            gedmo_translator:
                                type: annotation
                                prefix: Gedmo\Translator\Entity
                                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                                alias: GedmoTranslator # (optional) it will default to the name set for the mapping
                                is_bundle: false
                            gedmo_loggable:
                                type: annotation
                                prefix: Gedmo\Loggable\Entity
                                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                                alias: GedmoLoggable # (optional) it will default to the name set for the mappingmapping
                                is_bundle: false
                            gedmo_tree:
                                type: annotation
                                prefix: Gedmo\Tree\Entity
                                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                                alias: GedmoTree # (optional) it will default to the name set for the mapping
                                is_bundle: false

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# JMS i18n Routing Configuration (required for locale paths in URIs)

jms_i18n_routing:
    default_locale: "%locale%"
    locales: [ru, en]
    strategy: prefix_except_default

# FOSUser Bundle Configuration

fos_user:
  db_driver: orm
  firewall_name: main
  user_class: AppBundle\Entity\User
  from_email:
    address: "%mailer_user%"
    sender_name: "%mailer_user%"

# StofDoctrineExtensions library Configuration

stof_doctrine_extensions:
  default_locale: en_US
  translation_fallback: true
  orm:
    default:
      tree: true
      sluggable: true
      timestampable: true
      loggable: true

# Monolog extension configuration

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        console:
            type:   console
            channels: ["!event", "!doctrine"]
        #database:
         #   type: stream
          #  path: "%kernel.logs_dir%/doctrine_%kernel.environment%.log"
           # channels: [doctrine]

# FOSElasticaBundle (search&filter engine) library configuration

fos_elastica:
    #serializer: ~
    clients:
        default:
            host: "%fos_elastica.host%"
            port: "%fos_elastica.port%"
    indexes:
        lencor_archive:
            index_name: archive_entries
            client: default
            types:
              archive_factories:
                mappings:
                  id: ~
                  factoryName: ~
              archive_settings:
                mappings:
                  id: ~
                  factoryId: ~
                  settingsName: ~
                _parent:
                  type: "archive_factories"
                  identifier: "id"
                  property: "id"
              archive_entries:
                mappings:
                  factory:
                      type: "object"
                      properties:
                        id: ~
                        factoryName: ~
                  setting:
                      type: "object"
                      properties:
                        id: ~
                        settingName: ~
                  year:
                    type: integer
                  archiveNumber: ~
                  registerNumber: ~
                  contractNumber: ~
                  fullConclusionName: ~
                  cataloguePath: ~
                  lastModified: ~
                  modifiedByUserId: ~
                  deleteMark: ~
                persistence:
                  driver: orm
                  model: AppBundle\Entity\ArchiveEntryEntity
                  finder: ~
                  provider: ~
                  listener: ~
                  repository: ~ #AppBundle\Repository\ArchiveEntrySearchRepository
                  elastica_to_model_transformer:
                    query_builder_method: createEntriesAndErrorsQueryBuilder

# Vich Uploader Bundle configuration
#to be removed, not used anywhere !

vich_uploader:
    db_driver: orm
    mappings:
      documents:
        uri_prefix: /Resources/files
        upload_destination: '%kernel.root_dir%/Resources/files'
        inject_on_load: false
        delete_on_update: true
        delete_on_remove: true

# Sensio Framework Extra Bundle configuration
sensio_framework_extra:
  request:
    converters: true
    auto_convert: false

