app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    #prefix: /{_locale}

#FOSUser Bundle Configuration

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"
  #prefix: /{_locale}