# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

    filesize_conversion_extension.twig.extension.class: AppBundle\Twig\FileSizeConverterExtension

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

  # default configuration for services in *this* file
  _defaults:
    # automatically injects dependencies in your services
    autowire: true
    # automatically registers your services as commands, event subscribers, etc.
    autoconfigure: true

  # makes classes in src/AppBundle available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  AppBundle\:
    resource: '../../src/AppBundle/*'
    # you can exclude directories or files
    # but if a service is unused, it's removed anyway
    exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

  # controllers are imported separately to make sure they're public
  # and have a tag that allows actions to type-hint services
  AppBundle\Controller\:
    resource: '../../src/AppBundle/Controller'
    public: true
    tags: ['controller.service_arguments']

  AppBundle\AppBundle:
    # application forms
    form:
      archiveentryaddform:
        class: AppBundle\Form\ArchiveEntryAddForm
        arguments: ['@doctrine.orm.entity_manager']
        tags:
          - { name: form.type }
      archiveentrysearchform:
        class: AppBundle\Form\ArchiveEntrySearchForm
        arguments: ['@doctrine.orm.entity_manager']
        tags:
          - { name: form.type }
      folderaddform:
        class: AppBundle\Form\FolderAddForm
        arguments: ['@doctrine.orm.entity_manager']
        tags:
          - { name: form.type }
      fileaddform:
        class: AppBundle\Form\FileAddForm
        arguments: ['@doctrine.orm.entity_manager']
        tags:
          - { name: form.type }
      logsearchform:
        class: AppBundle\Form\LogSearchForm
        tags:
          - { name: form.type}
      logrowscountform:
        class: AppBundle\Form\LogRowsCountForm
        tags:
          - { name: form.type}
    # application services
    service:
      folderservice:
        class: AppBundle\Service\FolderService
        arguments: ['@doctrine.orm.entity_manager']
      fileservice:
        class: AppBundle\Service\FileService
        arguments: ['@doctrine.orm.entity_manager', '@service_container']
      archiveentryservice:
        class: AppBundle\Service\ArchiveEntryService
        arguments: ['@doctrine.orm.entity_manager', '@service_container']

  #jms_serializer:
    #class: JMS\SerializerBundle\JMSSerializerBundle

# required to implement binary tree select list options
# https://github.com/Yavin/symfony-form-tree

    symfony.form.type_guesser.tree:
        class: Yavin\Symfony\Form\Type\TreeTypeGuesser
        arguments: [ "@doctrine" ]
        tags:
            - { name: form.type_guesser }
    filesize_conversion.twig.extension:
        class: "%filesize_conversion_extension.twig.extension.class%"
        tags:
            - { name: twig.extension }